// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Solid.Infra.Data;
using System;

namespace Solid.Infra.Data.Migrations
{
    [DbContext(typeof(LibraryContext))]
    [Migration("20190724144137_LibraryDB-V1")]
    partial class LibraryDBV1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("Solid.Domain.Entity.BookEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("IdCategoryId");

                    b.Property<string>("NmBook");

                    b.Property<decimal>("VrBook");

                    b.HasKey("Id");

                    b.HasIndex("IdCategoryId");

                    b.ToTable("Book");
                });

            modelBuilder.Entity("Solid.Domain.Entity.CategoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("NmCategory");

                    b.HasKey("Id");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("Solid.Domain.Entity.BookEntity", b =>
                {
                    b.HasOne("Solid.Domain.Entity.CategoryEntity", "IdCategory")
                        .WithMany()
                        .HasForeignKey("IdCategoryId");
                });
#pragma warning restore 612, 618
        }
    }
}
